general:
  delegate_server_host: localhost
  delegate_server_port: 3000
  bc_key: false # You must run: `php artisan orm:bckey` on the ORM Core API server to generate a BC_KEY, after that paste the key string here